version: "3.9"

services:
  esphome:
    image: ghcr.io/esphome/esphome:2025.12.2
    container_name: esphome
    volumes:
      - ./esphome:/config
    ports:
      - "6052:6052"
    environment:
      - TZ=Europe/Warsaw
    restart: unless-stopped
